"""empty message

Revision ID: 2ebb78e9a3ea
Revises: aa7829984e2a
Create Date: 2022-11-09 15:36:38.121046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ebb78e9a3ea'
down_revision = 'aa7829984e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_firstname', sa.String(length=120), nullable=False),
    sa.Column('user_lastname', sa.String(length=120), nullable=False),
    sa.Column('user_username', sa.String(length=64), nullable=False),
    sa.Column('user_created_at', sa.DateTime(), nullable=True),
    sa.Column('user_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_firstname'), 'users', ['user_firstname'], unique=False)
    op.create_index(op.f('ix_users_user_lastname'), 'users', ['user_lastname'], unique=False)
    op.create_index(op.f('ix_users_user_username'), 'users', ['user_username'], unique=True)
    op.drop_index('ix_user_user_firstname', table_name='user')
    op.drop_index('ix_user_user_lastname', table_name='user')
    op.drop_index('ix_user_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_firstname', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('user_lastname', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('user_username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_pkey')
    )
    op.create_index('ix_user_user_username', 'user', ['user_username'], unique=False)
    op.create_index('ix_user_user_lastname', 'user', ['user_lastname'], unique=False)
    op.create_index('ix_user_user_firstname', 'user', ['user_firstname'], unique=False)
    op.drop_index(op.f('ix_users_user_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_lastname'), table_name='users')
    op.drop_index(op.f('ix_users_user_firstname'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
