"""added otp

Revision ID: 515a7e1deaae
Revises: 26eb2a5eee7e
Create Date: 2022-11-13 14:53:37.050522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515a7e1deaae'
down_revision = '26eb2a5eee7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp', sa.String(length=16), nullable=True))
    op.create_unique_constraint(None, 'users', ['otp'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'otp')
    # ### end Alembic commands ###
