"""empty message

Revision ID: 51a378ce978c
Revises: a5966650c6ec
Create Date: 2022-11-10 15:09:50.944462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a378ce978c'
down_revision = 'a5966650c6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_firstname', sa.String(length=120), nullable=False),
    sa.Column('user_lastname', sa.String(length=120), nullable=False),
    sa.Column('user_username', sa.String(length=64), nullable=False),
    sa.Column('user_created_at', sa.DateTime(), nullable=True),
    sa.Column('user_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_firstname'), 'users', ['user_firstname'], unique=False)
    op.create_index(op.f('ix_users_user_lastname'), 'users', ['user_lastname'], unique=False)
    op.create_index(op.f('ix_users_user_username'), 'users', ['user_username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_lastname'), table_name='users')
    op.drop_index(op.f('ix_users_user_firstname'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
