"""Users Table

Revision ID: aa7829984e2a
Revises: 
Create Date: 2022-11-09 10:08:50.351013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7829984e2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_firstname', sa.String(length=120), nullable=True),
    sa.Column('user_lastname', sa.String(length=120), nullable=True),
    sa.Column('user_username', sa.String(length=64), nullable=True),
    sa.Column('user_created_at', sa.DateTime(), nullable=True),
    sa.Column('user_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_firstname'), 'user', ['user_firstname'], unique=False)
    op.create_index(op.f('ix_user_user_lastname'), 'user', ['user_lastname'], unique=False)
    op.create_index(op.f('ix_user_user_username'), 'user', ['user_username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_user_lastname'), table_name='user')
    op.drop_index(op.f('ix_user_user_firstname'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
