"""wtf

Revision ID: d88d3fab6988
Revises: 2e33f4254c4a
Create Date: 2022-11-16 15:53:50.414587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88d3fab6988'
down_revision = '2e33f4254c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_firstname', sa.String(length=120), nullable=False),
    sa.Column('user_lastname', sa.String(length=120), nullable=False),
    sa.Column('user_username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('user_created_at', sa.DateTime(), nullable=True),
    sa.Column('user_updated_at', sa.DateTime(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_firstname'), 'users', ['user_firstname'], unique=False)
    op.create_index(op.f('ix_users_user_lastname'), 'users', ['user_lastname'], unique=False)
    op.create_index(op.f('ix_users_user_username'), 'users', ['user_username'], unique=True)
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=False),
    sa.Column('start_year', sa.String(length=5), nullable=False),
    sa.Column('end_year', sa.String(length=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_jobs_company_name'), 'jobs', ['company_name'], unique=False)
    op.create_index(op.f('ix_jobs_job_title'), 'jobs', ['job_title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_job_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_name'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_user_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_lastname'), table_name='users')
    op.drop_index(op.f('ix_users_user_firstname'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
