"""removed otp moved to cache

Revision ID: e4c011688fa8
Revises: f1aaaefd0a65
Create Date: 2022-11-14 15:45:01.565162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c011688fa8'
down_revision = 'f1aaaefd0a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_otp_key', 'users', type_='unique')
    op.drop_column('users', 'otp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_otp_key', 'users', ['otp'])
    # ### end Alembic commands ###
